namespace CryptoStockMVC.Models
{
    public class CoinImages
    {
        private Dictionary<string, string> _pathes;

        public CoinImages()
        {
            _pathes = new Dictionary<string, string>()
            {
                {"BTC","/images/coins-images/bitcoin.png" },
                {"ETH","/images/coins-images/etherium.png"},
                {"USDT","/images/coins-images/tether.png" },
                {"USDC","/images/coins-images/usd_coin.png" },
                {"BNB","/images/coins-images/bnb.png" },
                {"BUSD","/images/coins-images/binance_usd.png" },
                {"XRP","/images/coins-images/xrp.png" },
                {"ADA","/images/coins-images/cardano.png" },
                {"SOL","/images/coins-images/solana.png" },
                {"DOGE","/images/coins-images/dogecoin.png" },
                {"DOT","/images/coins-images/polkadot.png" },
                {"SHIB","/images/coins-images/shiba_inu.png" },
                {"DAI","/images/coins-images/dai.png" },
                {"MATIC","/images/coins-images/polygon.png" },
                {"AVAX","/images/coins-images/avalanche.png" },
                {"TRX","/images/coins-images/tron.png" },
                {"WBTC","/images/coins-images/wrapped_bitcoin.png" },
                {"UNI","/images/coins-images/uniswap.png" },
                {"ETC","/images/coins-images/etherium_classic.png" },
                {"LEO","/images/coins-images/unus_sed_leo.png" },
                {"LTC","/images/coins-images/litecoin.png" },
                {"FTT","/images/coins-images/ftx_token.png" },
                {"ATOM","/images/coins-images/cosmos.png" },
                {"LINK","/images/coins-images/chainlink.png" },
                {"CRO","/images/coins-images/cronos.png" },
                {"NEAR","/images/coins-images/near_protocol.png" },
                {"XMR","/images/coins-images/monero.png" },
                {"XLM","/images/coins-images/stellar.png" },
                {"BCH","/images/coins-images/bitcoin_cash.png" },
                {"FLOW","/images/coins-images/flow.png" },
                {"ALGO","/images/coins-images/binance_usd.png" },
                {"VET","/images/coins-images/binance_usd.png" },
                {"EOS","/images/coins-images/binance_usd.png" },
                {"FIL","/images/coins-images/binance_usd.png" },
                {"ICP","/images/coins-images/binance_usd.png" },
                {"APE","/images/coins-images/binance_usd.png" },
                {"MANA","/images/coins-images/binance_usd.png" },
                {"SAND","/images/coins-images/binance_usd.png" },
                {"XTZ","/images/coins-images/binance_usd.png" },
                {"HBAR","/images/coins-images/binance_usd.png" },
                {"CHZ","/images/coins-images/binance_usd.png" },
                {"QNT","/images/coins-images/binance_usd.png" },
                {"EGLD","/images/coins-images/binance_usd.png" },
                {"THETA","/images/coins-images/binance_usd.png" },
                {"AAVE","/images/coins-images/binance_usd.png" },
                {"AXS","/images/coins-images/binance_usd.png" },
                {"TUSD","/images/coins-images/binance_usd.png" },
                {"OKB","/images/coins-images/binance_usd.png" },
                {"BSV","/images/coins-images/binance_usd.png" },
                {"ZEC","/images/coins-images/binance_usd.png" },
                {"KCS","/images/coins-images/binance_usd.png" },
                {"USDP","/images/coins-images/binance_usd.png" },
                {"BTT","/images/coins-images/binance_usd.png" },
                {"HNT","/images/coins-images/binance_usd.png" },
                {"MIOTA","/images/coins-images/binance_usd.png" },
                {"MKR","/images/coins-images/binance_usd.png" },
                {"GRT","/images/coins-images/binance_usd.png" },
                {"FTM","/images/coins-images/binance_usd.png" },
                {"KLAY","/images/coins-images/binance_usd.png" },
                {"XEC","/images/coins-images/binance_usd.png" },
                {"HT","/images/coins-images/binance_usd.png" },
                {"USDD","/images/coins-images/binance_usd.png" },
                {"RUNE","/images/coins-images/binance_usd.png" },
                {"NEO","/images/coins-images/binance_usd.png" },
                {"SNX","/images/coins-images/binance_usd.png" },
                {"USDN","/images/coins-images/binance_usd.png" },
                {"LDO","/images/coins-images/binance_usd.png" },
                {"CRV","/images/coins-images/binance_usd.png" },
                {"PAXG","/images/coins-images/binance_usd.png" },
                {"CAKE","/images/coins-images/binance_usd.png" },
                {"NEXO","/images/coins-images/binance_usd.png" },
                {"BAT","/images/coins-images/binance_usd.png" },
                {"WAVES","/images/coins-images/binance_usd.png" },
                {"DASH","/images/coins-images/binance_usd.png" },
                {"ZIL","/images/coins-images/binance_usd.png" },
                {"STX","/images/coins-images/binance_usd.png" },
                {"LRC","/images/coins-images/binance_usd.png" },
                {"ENJ","/images/coins-images/binance_usd.png" },
                {"DCR","/images/coins-images/binance_usd.png" },
                {"GMT","/images/coins-images/binance_usd.png" },
                {"MINA","/images/coins-images/binance_usd.png" },
                {"KAVA","/images/coins-images/binance_usd.png" },
                {"BTG","/images/coins-images/binance_usd.png" },
                {"GNO","/images/coins-images/binance_usd.png" },
                {"1INCH","/images/coins-images/binance_usd.png" },
                {"XEM","/images/coins-images/binance_usd.png" },
                {"FEI","/images/coins-images/binance_usd.png" },
                {"TWT","/images/coins-images/binance_usd.png" },
                {"AR","/images/coins-images/binance_usd.png" },
                {"KSM","/images/coins-images/binance_usd.png" },
                {"CELO","/images/coins-images/binance_usd.png" },
                {"ANKR","/images/coins-images/binance_usd.png" },
                {"CVX","/images/coins-images/binance_usd.png" },
                {"HOT","/images/coins-images/binance_usd.png" },
                {"GALA","/images/coins-images/binance_usd.png" },
                {"XDC","/images/coins-images/binance_usd.png" },
                {"COMP","/images/coins-images/binance_usd.png" },
                {"YFI","/images/coins-images/binance_usd.png" },
                {"QTUM","/images/coins-images/binance_usd.png" },
                {"GT","/images/coins-images/binance_usd.png" },

            };
        }

        public string GetPath(string symbol)
        {
            _pathes.TryGetValue(symbol, out string value);
            return value ?? string.Empty;
        }
    }

    
}
